device_name: fakeitaliradio
device_type: speaker
audio_backend: pipe
audio_output_pipe: /tmp/fakeitaliradio.pcm
audio_output_pipe_format: s16le
bitrate: 320
volume_steps: 100
initial_volume: 100
credentials:
  type: zeroconf
server:
  enabled: true
  port: 3678
