#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

RUNTIME_ROOT="$ROOT/.context/conductor"
export MAMMAMIRADIO_BIND_HOST="${MAMMAMIRADIO_BIND_HOST:-127.0.0.1}"
export MAMMAMIRADIO_PORT="${MAMMAMIRADIO_PORT:-${CONDUCTOR_PORT:-8000}}"
export MAMMAMIRADIO_TMP_DIR="${MAMMAMIRADIO_TMP_DIR:-$RUNTIME_ROOT/tmp}"
export MAMMAMIRADIO_CACHE_DIR="${MAMMAMIRADIO_CACHE_DIR:-$RUNTIME_ROOT/cache}"
export MAMMAMIRADIO_GO_LIBRESPOT_CONFIG_DIR="${MAMMAMIRADIO_GO_LIBRESPOT_CONFIG_DIR:-$RUNTIME_ROOT/go-librespot}"

if [ -n "${CONDUCTOR_WORKSPACE_NAME:-}" ]; then
  export MAMMAMIRADIO_FIFO_PATH="${MAMMAMIRADIO_FIFO_PATH:-/tmp/mammamiradio-${CONDUCTOR_WORKSPACE_NAME}.pcm}"
fi

if [ -n "${CONDUCTOR_PORT:-}" ] && [ -z "${MAMMAMIRADIO_GO_LIBRESPOT_PORT:-}" ]; then
  export MAMMAMIRADIO_GO_LIBRESPOT_PORT="$((CONDUCTOR_PORT + 1))"
fi

mkdir -p "$MAMMAMIRADIO_TMP_DIR" "$MAMMAMIRADIO_CACHE_DIR" "$MAMMAMIRADIO_GO_LIBRESPOT_CONFIG_DIR"

exec ./start.sh
